### ISSUE TITLE
Clock and chrome chashing after removal of module

### ISSUE THREAD

**Issue by Khuerustom** [Magisk-Modules-Repo/MIUI-10-Camera#12]
Bug reports and feature requests
- I've read the guidelines for Contributing to Pixel 2 Experience
- This is a bug report for the Pixel 2 Experience module repo and not for Pixel Experience ROM
- I've read the Readme for this module and followed them
- eplace any X with your information.

What is the current behavior?

Having issue after uninstalling on my moto g5s plus. Google clock app and chrome is crashing. Installed miui 10 cam again and the problem was gone but reappeared as soon as I un installed the module. Need help.
what is the expected or desired behavior?

Everything should work after uninstall

Please provide steps to reproduce, including full log output:

X

Please describe your local environment:

Android version: 8.1.0

ROM: stock

Pixel 2 Experience module version: X

Where did the bug happen? Launcher or theme? Others?

Google Clock, chrome

Please provide a screen or logcat (if possible):

X

Other relevant information:

X

**Comment by joeyhuab** [comment]
Install the module twice to fully remove it from Magisk. Read the readme. Issue is not with the module.
